# Conexión con Google Drive

En esta sección, estableceremos una conexión entre Google Colab y Google Drive para acceder a nuestros archivos de datos. Es necesario que nuestros archivos esten un Mi unidad o como acceso directo para establecer una conexión, además de dar los permisos que nos pida al ejecutar el siguiente comando:

```python
from google.colab import drive
# Montar Google Drive
drive.mount('/content/drive')
```
Luego de ejecutar el seguiente comando aparecera:

![](https://drive.google.com/uc?id=1wBQUjXK7UXNshMXxeiQPfjsVLFmyecU_)

Damos click en Conectar con Google Drive, aparecera la siguiente ventana emergente donde pedira una cuenta de Gmail.

![](https://drive.google.com/uc?id=1bqoVdGJsEuqH8bQXZcandDk_6dtn72zS)

Seleccionamos nuestra cuenta.

![](https://drive.google.com/uc?id=1I6jo_OzGNV6pisDNSQ7pzxsjsjWYCp_y)

Finalmente permitimos el acceso.

![](https://drive.google.com/uc?id=1vQJGUnwN3KfXlWmCJmrJRo56t-7fJPTC)

In [8]:
from google.colab import drive
drive.mount('/content/drive') # Conexión con mi unidad en Google Drive

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Manejo de Data Frame

Para el desarrollo de este notebook, se utilizó una base de datos proveniente de [kaggle](https://www.kaggle.com/datasets/imakash3011/customer-personality-analysis) que contiene información de

Luego de establecer una conexión con Google Drive, utilizando la librería pandas, podemos copiar el path de nuestro archivo para leer los datos con pandas.

![](https://drive.google.com/uc?id=1vX_jc_aGw4b_BEKVquPCblbX-Csw27OL)

Se ubica el archivo, dar click derecho y copar ruta.

In [9]:
import pandas as pd # Manejo de Data Frame
# Librerias para gráficos
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import numpy as np # Arreglos matriciales


Para la lectura de datos, los datos de este ejercicio esta delimitado por "\t".

En pd.read_csv, existe un argumento sep donde delimita los registros en el archivo de texto.

In [10]:
datos= pd.read_csv("/content/drive/MyDrive/Aprendizaje no supervisado/Notebook/datos/marketing_campaign.csv",sep= "\t") # copiar y pegar la ruta

In [11]:
datos # mostrar los datos

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [12]:
datos.head(10) # Muestra los primeros 10 registros

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
5,7446,1967,Master,Together,62513.0,0,1,09-09-2013,16,520,...,6,0,0,0,0,0,0,3,11,0
6,965,1971,Graduation,Divorced,55635.0,0,1,13-11-2012,34,235,...,6,0,0,0,0,0,0,3,11,0
7,6177,1985,PhD,Married,33454.0,1,0,08-05-2013,32,76,...,8,0,0,0,0,0,0,3,11,0
8,4855,1974,PhD,Together,30351.0,1,0,06-06-2013,19,14,...,9,0,0,0,0,0,0,3,11,1
9,5899,1950,PhD,Together,5648.0,1,1,13-03-2014,68,28,...,20,1,0,0,0,0,0,3,11,0

In [13]:
datos.tail() # Muestra los 5 ultimos registros

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [14]:
datos.shape # Dimensión de los datos

(2240, 29)

In [15]:
datos.columns # Nombre de las columnas

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

In [16]:
datos["Education"] # Seleccionamos educación

0       Graduation
1       Graduation
2       Graduation
3       Graduation
4              PhD
           ...
2235    Graduation
2236           PhD
2237    Graduation
2238        Master
2239           PhD
Name: Education, Length: 2240, dtype: object

In [21]:
datos[['Year_Birth', 'Education', 'Marital_Status', 'Income' ]] # Selección de multiples columnas

      Year_Birth   Education Marital_Status   Income
0           1957  Graduation         Single  58138.0
1           1954  Graduation         Single  46344.0
2           1965  Graduation       Together  71613.0
3           1984  Graduation       Together  26646.0
4           1981         PhD        Married  58293.0
...          ...         ...            ...      ...
2235        1967  Graduation        Married  61223.0
2236        1946         PhD       Together  64014.0
2237        1981  Graduation       Divorced  56981.0
2238        1956      Master       Together  69245.0
2239        1954         PhD        Married  52869.0

[2240 rows x 4 columns]

In [18]:
datos.describe( ) # Estadísticos de resumen

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [ ]:
datos.describe( include="O" ) # Estadísticos de resumen para variables categorícas